USE NPS
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT id FROM sysobjects WHERE name = 'StatusAtendimento')
BEGIN
	CREATE TABLE dbo.StatusAtendimento
	(
		CodStatusAtendimento	TINYINT			NOT NULL,
		Descricao							VARCHAR(50)	NULL,

		CONSTRAINT PK_StatusAtendimento
		PRIMARY KEY CLUSTERED (CodStatusAtendimento ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80)
		ON [PRIMARY]

	) ON [PRIMARY]
END
GO