USE NPS
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT id FROM sysobjects WHERE name = 'Motivo')
BEGIN
	CREATE TABLE dbo.Motivo
	(
		CodMotivo		SMALLINT			NOT NULL,
		Descricao		NVARCHAR(50)	NULL,	
		Ordenacao		TINYINT				NULL,

		CONSTRAINT PK_Motivo
		PRIMARY KEY CLUSTERED (CodMotivo ASC)
		WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) 
		ON [PRIMARY],

	) ON [PRIMARY]
END
GO